site_name: Az MI Fluencia Keretrendszer
docs_dir: course/hu
repo_url: https://github.com/newpush-labs/newpush-ai-fluency
repo_name: newpush-labs/newpush-ai-fluency
edit_uri: edit/main/course/hu/
copyright: >
  Copyright &copy; 2024 NewPush Labs –
  <a href="#__consent">Cookie beállítások módosítása</a>
theme:
  name: material
  language: hu
  logo: images/newpush.svg
  favicon: images/newpush.svg
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - content.action.edit
  custom_dir: course/hu/custom_theme
extra_css:
  - custom.css
extra_javascript:
  - js/abbreviations-first-only.js
plugins:
  - privacy
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
extra:
  analytics:
    provider: custom
  consent:
    title: Cookie hozzájárulás
    description: >-
      Sütiket (cookie-kat) használunk az ismételt látogatások és beállítások felismerésére,
      valamint dokumentációnk hatékonyságának mérésére és annak megállapítására, hogy a
      felhasználók megtalálják-e amit keresnek. Az Ön hozzájárulásával segít nekünk
      dokumentációnk jobbá tételében.
    actions:
      - accept
      - manage
    cookies:
      github:
        name: GitHub
        checked: true

  links:
    - name: Kapcsolat
      url: https://www.newpush.com
    - name: Visszajelzés
      url: https://docs.google.com/forms/d/e/1FAIpQLSdEDQvOwm8OylDCpRQCVp4sRyNdNfFrTfnB7_vgd62dXj6C5Q/viewform
watch:
  - includes
nav:
  - 'Kezdőlap': 'index.md'
  - 'Bevezetés az MI Fluenciába': '01-bevezetes-az-mi-fluenciaba.md'
  - 'Az MI Fluencia Keretrendszer': '02-az-mi-fluencia-keretrendszer.md'
  - 'Mélymerülés 1: Mi a Generatív MI?': '03-melymerules-1-mi-a-generativ-mi.md'
  - 'Delegáció': '04-delegacio.md'
  - 'A Delegáció Alkalmazása': '05-a-delegacio-alkalmazasa.md'
  - 'Leírás': '06-leiras.md'
  - 'Mélymerülés 2: Hatékony Promptolási Technikák': '07-melymerules-2-hatekony-promptolasi-technikak.md'
  - 'Megkülönböztetés': '08-megkulonboztetes.md'
  - 'A Leírás-Megkülönböztetés Hurok': '09-a-leiras-megkulonboztetes-hurok.md'
  - 'Gondosság': '10-gondossag.md'
  - 'Összegzés és Tanúsítvány': '11-osszegzes-es-tanusitvany.md'
  - 'További Gyakorlatok': '12-tovabbi-gyakorlatok.md'
  - 'Kurzus Anyagok': 'kurzus-anyagok.md'